// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlGgOGzc5XjKRVAzYmXvu9kAGwp7fwPIY',
    appId: '1:46693241781:web:16deca4c176a7b6be93ffc',
    messagingSenderId: '46693241781',
    projectId: 'appforasm',
    authDomain: 'appforasm.firebaseapp.com',
    storageBucket: 'appforasm.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3_xfJG4HxiKxgZ6WRgMPxrLO-yUNsJww',
    appId: '1:46693241781:android:6e97858d6c689bbfe93ffc',
    messagingSenderId: '46693241781',
    projectId: 'appforasm',
    storageBucket: 'appforasm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkjm3t7QEoJGvSlJHZWmH_ogCNNjzfSaY',
    appId: '1:46693241781:ios:3b94c284e72f8befe93ffc',
    messagingSenderId: '46693241781',
    projectId: 'appforasm',
    storageBucket: 'appforasm.appspot.com',
    iosBundleId: 'com.example.minimalsocialapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkjm3t7QEoJGvSlJHZWmH_ogCNNjzfSaY',
    appId: '1:46693241781:ios:8012b94ed2ddc6eee93ffc',
    messagingSenderId: '46693241781',
    projectId: 'appforasm',
    storageBucket: 'appforasm.appspot.com',
    iosBundleId: 'com.example.minimalsocialapp.RunnerTests',
  );
}
